name: 'Compose Setup' 
description: 'Set Up Codection Compose' 

runs: 
  using: 'composite' 
  steps: 
    - name: setup codection-compose
      run: |
        git clone https://github.com/SWM-Codection/Codection-Compose .codection
        cd .codection
        chmod +x ./bootstrap.sh
        /bin/bash ./bootstrap.sh

    - name: run codection-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with: 
        cwd: ${{github.workspace}}/.codection
        compose-file: ./docker-compose.yml
