name: CI with DockerCompose 

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 
jobs:
  run-compose:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout git submodules 
      uses: actions/checkout@v4

    - name: setup java 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: executing bootstrap.sh 
      run: chmod +x ./bootstrap.sh && /bin/bash ./bootstrap.sh

    - name: setting up docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with: 
        compose-file: ./docker-compose.yml
    
  
