name: CI with DockerCompose 

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 
  workflow_call:
jobs:
  run-compose:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout git submodules 
      uses: actions/checkout@v4

    - name: setup java 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: setup codection-compose
      run: | 
        git clone https://github.com/SWM-Codection/Codection-Compose .codection
        chmod +x ./.codection/bootstrap.sh
        /bin/bash ./.codection/bootstrap.sh

    - name: run codectioncompose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with: 
        compose-file: ./.codection/docker-compose.yml
    
  
